sightings/urls.py
from django.urls import path
from . import views

app_name = 'squirrel'
urlpatterns = [
        path('',views.all_list,name='all_list'),
        path('add/',views.add, name='add'),
        path('stats/',views.stats,name='stats'),
        path('<str:unique_squirrel_id>/', views.update,name='update'),
        ]

squirrel/urls.py
from django.contrib import admin
from django.urls import path,include
from sightings.views import map_plot
urlpatterns = [
    path('sightings/',include('sightings.urls')),
    path('admin/', admin.site.urls),
    path('map/',map_plot),
]

sightings/models.py
from django.db import models
from django.utils.translation import gettext as _
import datetime
from django.utils import timezone
class Squirrel(models.Model):
    latitude = models.DecimalField(
        help_text =_('Latitude'),
        max_digits = 30,
        decimal_places = 20,
    )
    
    longitude = models.DecimalField(
        help_text =_('Longitude'),
        max_digits = 30,
        decimal_places = 20,
    )
    
    unique_squirrel_id = models.CharField(
        help_text = _('Unique Squirrel ID'),
        max_length = 30,
    )
    
    AM = 'AM'
    PM = 'PM'
    SHIFT_CHOICES = (
        (AM, 'AM'),
        (PM, 'PM'),
    )
    
    shift = models.CharField(
        help_text=_('Shift'),
        max_length=3,
        choices=SHIFT_CHOICES,
    )


    date = models.DateField(
        help_text=_('Date'),
        default=timezone.now,
   )


    ADULT = 'Adult'
    JUVENILE = 'Juvenile'

    AGE_CHOICES = (
        (ADULT, 'Adult'),
        (JUVENILE, 'Juvenile'),
    )

    age = models.CharField(
        help_text=_('Age'),
        max_length=15,
        choices=AGE_CHOICES,
    )

    GRAY = 'Gray'
    CINNAMON = 'Cinnamon'
    BLACK = 'Black'

    COLOR_CHOICES = (
        (GRAY, 'Gray'),
        (CINNAMON, 'Cinnamon'),
        (BLACK, 'Black')
    )

    primary_fur_color = models.CharField(
        help_text=_('Primary Fur Color'),
        max_length=15,
        choices=COLOR_CHOICES,
    )

    GROUND_PLANE = 'Ground Plane'
    ABOVE_GROUND = 'Above Ground'

    LOCATION_CHOICES = (
        (GROUND_PLANE, 'Ground Plane'),
        (ABOVE_GROUND, 'Above Ground'),
    )

    location = models.CharField(
        help_text=_('Location'),
        max_length=20,
        choices=LOCATION_CHOICES,
    )

    specific_location = models.CharField(
        help_text=_('Specific Location'),
        max_length=50,
        null=True,blank=True,
    )

    TRUE = 'true'
    FALSE = 'false'

    BINARY_CHOICES = (
        (TRUE, 'True'),
        (FALSE, 'False'),
    )

    running = models.CharField(
        help_text=_('Running'),
        max_length=10,
        choices=BINARY_CHOICES,
    )

    chasing = models.CharField(
        help_text=_('Chasing'),
        max_length=10,
        choices=BINARY_CHOICES,
    )

    climbing = models.CharField(
        help_text=_('Climbing'),
        max_length=10,
        choices=BINARY_CHOICES,
    )

    eating = models.CharField(
        help_text=_('Eating'),
        max_length=10,
        choices=BINARY_CHOICES,
    )

    foraging = models.CharField(
        help_text=_('Foraging'),
        max_length=10,
        choices=BINARY_CHOICES,
    )

    other_activities = models.CharField(
        help_text=_('Other Activities'),
        max_length=50,
        null=True, blank=True,
    )

    kuks = models.CharField(
        help_text=_('Kuks'),
        max_length=10,
        choices=BINARY_CHOICES,
    )

    quaas = models.CharField(
        help_text=_('Quaas'),
        max_length=10,
        choices=BINARY_CHOICES,
    )

    moans = models.CharField(
        help_text=_('Moans'),
        max_length=10,
        choices=BINARY_CHOICES,
    )

    tail_flags = models.CharField(
        help_text=_('Tail Flags'),
        max_length=10,
        choices=BINARY_CHOICES,
    )

    tail_twitches = models.CharField(
        help_text=_('Tail Twitches'),
        max_length=10,
        choices=BINARY_CHOICES,
    )

    approaches = models.CharField(
        help_text=_('Approaches'),
        max_length=10,
        choices=BINARY_CHOICES,
    )

    indifferent = models.CharField(
        help_text=_('Indifferent'),
        max_length=10,
        choices=BINARY_CHOICES,
    )

    runs_from = models.CharField(
        help_text=_('Runs From'),
        max_length=10,
        choices=BINARY_CHOICES,
    )

    def __str__(self):
        return self.unique_squirrel_id

sightings/forms.py
from django.forms import ModelForm

from .models import Squirrel

class SquirrelForm(ModelForm):
    class Meta:
        model = Squirrel
        fields = '__all__'

sightings/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.template import RequestContext
from .models import Squirrel
from .forms import SquirrelForm
import datetime

def all_list(request):
    all_squirrel = Squirrel.objects.all()[::-1]
    return render(request, 'sightings/all_list.html',{'all_squirrels':all_squirrel})
    
def add(request):
    if request.method =='POST':
        form = SquirrelForm(request.POST)
        #check data with form
        if form.is_valid():
            form.save()
            return redirect(f'/sightings/all_list')
        
        else:
            context= {'form': form,
                      'error': 'The form was not valid. Please do it again.'}

            return render(request,'sightings/edit.html' , context) 
    else:
        form = SquirrelForm()
    context = {
            'form':form,
    }
    return render(request,'sightings/add.html',context)


def update(request,unique_squirrel_id):
    upup = Squirrel.objects.get(unique_squirrel_id=unique_squirrel_id)
    if request.method == 'POST':
        form = SquirrelForm(request.POST, instance=upup)
        if form.is_valid():
            form.save()
            return redirect(f'/sightings/{unique_squirrel_id}')
    
        else:
            context= {'form': form,
                      'error': 'The form was not valid. Please do it again.'}

            return render(request,'sightings/edit.html' , context)      

    else:
        form = SquirrelForm(instance=upup)
        context = {'form': form,
                  'instance': upup}

        return render(request, 'sightings/edit.html', context)


def stats(request):
    from collections import Counter
    
    # Running
    run_list = [value[0] for value in list(Squirrel.objects.all().values_list('running'))]
    run_dict = dict(Counter(run_list))
   

    # shift
    shift_list = [value[0] for value in list(Squirrel.objects.all().values_list('shift'))]
    shift_dict = dict(Counter(shift_list))

    #eating
    eat_list = [value[0] for value in list(Squirrel.objects.all().values_list('eating'))]
    eat_dict = dict(Counter(eat_list))
    
    #Climbing
    climb_list = [value[0] for value in list(Squirrel.objects.all().values_list('climbing'))]
    climb_dict = dict(Counter(climb_list))  
    
    lat_list =[value[0] for value in list(Squirrel.objects.all().values_list('latitude'))]
    n = len(lat_list) 
    get_sum = sum(lat_list) 
    mean = get_sum / n
    mean = round(mean,6)
   
    context = {'run_dict': run_dict,
               'shift_dict': shift_dict,
               'eat_dict': eat_dict,
               'climb_dict':climb_dict,
               'mean':mean,
              }
    
 
    
    return render(request,'sightings/stats.html',context)


def map_plot(request):
    n = 100
    latitudes = Squirrel.objects.values_list('latitude',flat=True)[:n]
    longitudes = Squirrel.objects.values_list('longitude',flat=True)[:n]
    uniqueids = Squirrel.objects.values_list('unique_squirrel_id',flat=True)[:n]

    mapmap = [ {"type": "Feature",
                        "properties": {
                            "id":  ident,
                            "popupContent":  "squirrel_id=%s" % (ident,) 
                            },
                        "geometry": {
                            "type": "Point",
                            "coordinates": [float(lon),float(lat)] }}
                        for ident,lon,lat in zip(uniqueids,longitudes,latitudes) ] 
    context = {'geo_json':mapmap}

    return render(request, 'sightings/map.html', context)

sightings/templates/sightings/add.html
<!DOCTYPE html>

<html>
<head>
<title>Create a New Sighting</title>
</head>

<h2>Create a New Sighting</h2>

<p class="all_list-box">
<a href="{% url 'squirrel:all_list' %}" class="all_list-link">Back to Squirrel List</a>
</p>

<body>
<form action="" method="POST">
{% csrf_token %}
Longitude: 
    <input type="text" name="longitude"><br>
Latitude: 
    <input type="text" name="latitude"><br>
Unique Squirrel ID: 
    <input type="text" name="unique_squirrel_id"><br>
Shift:
    <input type="radio" name="shift" value="AM" checked>AM
    <input type="radio" name="shift" value="PM">PM<br>
Date:
	<input type="date" name="date"><br>
Age: 
    <input type="radio" name="age" value="Adult" checked> Adult
    <input type="radio" name="age" value="Juvenile"> Juvenile<br>
Primary Fur Color: 
    <input type="radio" name="primary_fur_color" value="Gray" checked> Gray
    <input type="radio" name="primary_fur_color" value="Cinnamon"> Cinnamon
    <input type="radio" name="primary_fur_color" value="Black"> Black<br>
Location:
    <input type="radio" name="location" value="Ground Plane" checked> Ground Plane
    <input type="radio" name="location" value="Above Ground"> Above Ground<br>    
Specific Location:
    <input type="text" name="specific_location"><br>
Running:
    <input type="radio" name="running" value="true" checked> True
    <input type="radio" name="running" value="false"> False<br>    
Chasing:
    <input type="radio" name="chasing" value="true" checked> True
    <input type="radio" name="chasing" value="false"> False<br>   
Climbing:
    <input type="radio" name="climbing" value="true" checked> True
    <input type="radio" name="climbing" value="false"> False<br> 
Eating:
    <input type="radio" name="eating" value="true" checked> True
    <input type="radio" name="eating" value="false"> False<br>   
Foraging:
    <input type="radio" name="foraging" value="true" checked> True
    <input type="radio" name="foraging" value="false"> False<br>   
Other Activities:
    <input type="text" name="other_activities"/><br>
Kuks:
    <input type="radio" name="kuks" value="true" checked> True
    <input type="radio" name="kuks" value="false"> False<br>   
Quaas:
    <input type="radio" name="quaas" value="true" checked> True
    <input type="radio" name="quaas" value="false"> False<br>  
Moans:
    <input type="radio" name="moans" value="true" checked> True
    <input type="radio" name="moans" value="false"> False<br>  
Tail Flags:
    <input type="radio" name="tail_flags" value="true" checked> True
    <input type="radio" name="tail_flags" value="false"> False<br> 
Tail Twitches:
    <input type="radio" name="tail_twitches" value="true" checked> True
    <input type="radio" name="tail_twitches" value="false"> False<br>
Approaches:
    <input type="radio" name="approaches" value="true" checked> True
    <input type="radio" name="approaches" value="false"> False<br> 
Indifferent:
    <input type="radio" name="indifferent" value="true" checked> True
    <input type="radio" name="indifferent" value="false"> False<br> 
Runs From:
    <input type="radio" name="runs_from" value="true" checked> True
    <input type="radio" name="runs_from" value="false"> False<br> 

<input type="submit" value="Post">
{% if success %}<p><strong>{{ success }}</strong></p>{% endif %}
{% if date_error %}<p><strong>{{date_error}}</strong></p>{% endif %}
</form>

</body>

</html>

sightings/templates/sightings/all_list.html
<!DOCTYPE html>
<html>



<h1> HOME FOR SQUIRREL SIGHTINGS </h1>
<a href = "/map/">MAP </a><br>
<a href = "add/">ADD A SQUIRREL SIGHTING </a><br>
<a href ="stats/"> SIGHTING STATISTICS </a><br>
</br>

<h2> List of Squirrels </h2>
{% for s in all_squirrels %}
<li> 
	<a href = "{% url 'squirrel:update' s.unique_squirrel_id %}">{{s.unique_squirrel_id}}
	</a>

</li>
{% endfor %}
</html>

sightings/templates/sightings/edit.html
<!DOCTYPE html>
<html>
<title>Edit Sighting</title>
<h2>Squirrel ID: {{instance.unique_squirrel_id}}</h2>

<p class="all_list-box">
<a href="{% url 'squirrel:all_list' %}" class="all_list-link">Back to Squirrel List</a>
</p>

{% if error %}<p><strong>{{ error }}</strong></p>{% endif %}

<form method="POST" class="form">
    {% csrf_token %}
    {% for field in form %}
    	<div class="fieldWrapper">
    		{{field.label_tag}} {{field}}
	</div>
    {% endfor %}
    <button type="submit" class="save btn btn-default">Update</button>
{% if success %}<p><strong>{{ success }}</strong></p>{% endif %}

</form>

</html>

sightings/templates/sightings/main_list.html
<!DOCTYPE html>
<html>
<style>
li::before {
	content: "\1F43F";
	margin-left:-20px;
	margin-right:10px;
}
</style>
<title>Home Page: Squirrel List</title>

<h1> HOME PAGE </h1>
&#128205;<a href = "/map/">VIEW MAP! </a><br>
&#10071;<a href = "add/">ADD SQUIRREL SIGHTING! </a><br>
&#129488;<a href ="stats/"> INTERESTING STATISTICS! </a><br>
</br>

<h2> List of Squirrels </h2>
{% for s in all_squirrels %}
<li> <a href = "{% url 'squirrel:update' s.unique_squirrel_id %}">{{s.unique_squirrel_id}}</a></li>
{% endfor %}
</html>

sightings/templates/sightings/map.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet"
          href="https://unpkg.com/leaflet@1.5.1/dist/leaflet.css"
          integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
          crossorigin=""/>
    <!-- Make sure you put this AFTER Leaflet's CSS -->
    <script src="https://unpkg.com/leaflet@1.5.1/dist/leaflet.js"
            integrity="sha512-GffPMF3RvMeYyc1LWMHtK8EbPv0iNZ8/oTtHPx9/cc2ILxQ+u905qIwdpULaqDkyBKgOaB57QTMg7ztg8Jm2Og=="
            crossorigin=""></script>

    <style>
      html,body {
        height: 100%;
      }
    </style>
  </head>
  <body>
    <div id="map" class="container-fluid h-100"></div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- Leaflet JS -->
    <script>
        var map_center = [
            40.782091,  // Latitude
            -73.964285  // Longitude
        ];
        var zoom_level = 14;
        var map = L.map('map').setView(map_center, zoom_level);
        L.tileLayer('https://{server}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            server: 'a',  // can be 'a', 'b', or 'c'
            // must leave attribution in!
            attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
        }).addTo(map);
        <!-- L.Icon.Default.prototype.options.iconSize = 15; -->
        <!-- L.Icon.Default.prototype.options.iconAnchor = [0, 0]; -->
        <!-- L.Icon.Default.prototype.options.shadowSize = 15; -->
        <!-- L.Icon.Default.prototype.options.shadowAnchor = [0, 0]; -->
          
        var geojsonFeature = {{geo_json|safe}}
        L.geoJSON(geojsonFeature).addTo(map)
      
        
    </script>
  </body>
</html>

sightings/templates/sightings/stats.html
<!DOCTYPE html>
<html>
<head>
<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
th, td {
  text-align: center;
}
</style>

</head>
<body>

<h2> Statistics for squirrel sightings </h2>
  
<br>
<table style="width:40%">
        <tr>
                <th>Running</th>
                <th>Counts</th>
        </tr>
        {% for run, count in run_dict.items %}
                <tr>
                        <td>{{ run }}</td>
                        <td>{{ count }}</td>
                </tr>
        {% endfor %}
</table>
<br>
<table style="width:40%">
        <tr>
                <th>Shift</th>
                <th>Counts</th>
        </tr>
        {% for shift, count in shift_dict.items %}
                <tr>
                        <td>{{ shift }}</td>
                        <td>{{ count }}</td>
                </tr>
        {% endfor %}
</table>
<br>
<table style="width:40%">
        <tr>
                <th>Eating</th>
                <th>Counts</th>
        </tr>
        {% for eat, count in eat_dict.items %}
                <tr>
                        <td>{{ eat }}</td>
                        <td>{{ count }}</td>
                </tr>
        {% endfor %}
</table>
<br>
<table style="width:40%">
        <tr>
                <th>Climbing</th>
                <th>Counts</th>
        </tr>
        {% for climb, count in climb_dict.items %}
                <tr>
                        <td>{{ climb }}</td>
                        <td>{{ count }}</td>
                </tr>
        {% endfor %}
</table>
<br>
<li> The average of latitudes of squirrel sightings: {{mean}} </li>
</body>
</html>